// Generated by CoffeeScript 1.6.1
(function() {
  "user strict";
  var Room;

  Room = function(options) {
    this.server = options.server;
    this.name = options.name;
    this.key = "room:" + this.name;
    this.getClients = function(cb) {
      if (typeof cb !== 'function') {
        cb = function() {};
      }
      return this.server.clientRedis.smembers(this.key, cb);
    };
    this.add = function(socket) {
      var socket_id;
      socket_id = socket.id;
      if (this.server.clientRedis.sadd(this.key, socket_id)) {
        return socket.rooms.push(this.name);
      }
    };
    this.remove = function(socket) {
      var index, socket_id;
      socket_id = socket.id;
      if (this.server.clientRedis.srem(this.key, socket_id)) {
        index = socket.rooms.indexOf(this.name);
        if (index >= 0) {
          return socket.rooms.splice(index, 1);
        }
      }
    };
    this.emit = function(label, data) {
      return this.server.sendMessage(this.server.MSG_TYPES.ROOM_EMIT, {
        room: this.name,
        label: label,
        data: data
      });
    };
    return this;
  };

  module.exports = Room;

}).call(this);
